@echo off
setlocal

set "SCUM_DEPLOY_ROOT=%SCUM_DEPLOY_ROOT%"
if "%SCUM_DEPLOY_ROOT%"=="" set "SCUM_DEPLOY_ROOT=C:\new"

set "SCUM_RELOAD_RCON_PORT=%SCUM_RELOAD_RCON_PORT%"
if "%SCUM_RELOAD_RCON_PORT%"=="" set "SCUM_RELOAD_RCON_PORT=8038"

set "SCUM_RELOAD_RCON_HOST=%SCUM_RELOAD_RCON_HOST%"
if "%SCUM_RELOAD_RCON_HOST%"=="" set "SCUM_RELOAD_RCON_HOST=127.0.0.1"

set "SCUM_SERVER_ROOT=%SCUM_SERVER_ROOT%"
set "SCUM_RELOAD_LOOT_COMMAND=%SCUM_RELOAD_LOOT_COMMAND%"

powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0reload-scum-loot.ps1" -DeployRoot "%SCUM_DEPLOY_ROOT%" -ScumRoot "%SCUM_SERVER_ROOT%" -ExpectedRconPort %SCUM_RELOAD_RCON_PORT% -RconHost "%SCUM_RELOAD_RCON_HOST%" -ReloadCommand "%SCUM_RELOAD_LOOT_COMMAND%"
